#!/usr/bin/env bash
#
# This script wraps compatibility logic of guest agent's startup script
# runner. If compat manager is present run it, otherwise launch the
# known service binary.
#

if [ "$1" = "graceful-shutdown" ]; then
  /usr/bin/google_metadata_script_runner $1
elif [ -e /usr/bin/gce_compat_metadata_script_runner ]; then
  /usr/bin/gce_compat_metadata_script_runner $1
else
  /usr/bin/google_metadata_script_runner $1
fi